# Generated by Django 5.2.1 on 2025-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["email"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Token"),
        ),
    ]
