# Generated by Django 5.2.1 on 2025-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Reset password token"),
        ),
    ]
