# Generated by Django 5.2.1 on 2025-06-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "permissions": [("can_block_users", "Can block users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
