# Generated by Django 5.2.1 on 2025-05-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_mailing_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
