# Generated by Django 5.2.1 on 2025-05-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status", "sending_start"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
