# Generated by Django 5.2.1 on 2025-05-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt",
                to="messenger.mailing",
                verbose_name="Сообщение",
            ),
        ),
    ]
