# Generated by Django 5.2.1 on 2025-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0006_alter_attempt_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AlterField(
            model_name="attempt",
            name="attempt_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
    ]
