# Generated by Django 5.2.1 on 2025-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0007_alter_attempt_options_alter_attempt_attempt_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
