# Generated by Django 5.2.1 on 2025-06-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0008_alter_client_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name", "email"],
                "permissions": [
                    ("can_add_clients", "Can add clients"),
                    ("can_view_clients", "Can view clients"),
                    ("can_update_clients", "Can update clients"),
                    ("can_delete_clients", "Can delete clients"),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-status", "sending_start"],
                "permissions": [
                    ("can_add_mailings", "Can add mailings"),
                    ("can_view_mailings", "Can view mailings"),
                    ("can_update_mailings", "Can update mailings"),
                    ("can_delete_mailings", "Can delete mailings"),
                    ("can_start_mailings", "Can start mailings"),
                    ("can_end_mailings", "Can end mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
