# Generated by Django 5.2.1 on 2025-06-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0010_client_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["name", "email"], "verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-status", "sending_start"],
                "permissions": [("can_start_mailings", "Can start mailings"), ("can_end_mailings", "Can end mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
